### ISSUE TITLE
Uninformative unsat error

### ISSUE THREAD

**Issue by cournape** [enthought/sat-solver#132]
When using one of the `epd_full.yaml` scenario w/ the following request:

```
request:
  - operation: "install"
    requirement: "EPD"
  - operation: "install"
    requirement: "numpy > 1.8.0"
```

I see this:

```
UNSATISFIABLE: Conflicting requirements:
Requirement: 'numpy > 1.8.0-0'
    Install command rule (+numpy-1.8.0-1 | +numpy-1.8.0-2 | +numpy-1.8.0-3 | +numpy-1.8.1-1 | +numpy-1.8.1-2 | +numpy-1.8.1-3 | +numpy-1.9.2-1)

ELAPSED : Find Requirements    : 1.224041e-03
ELAPSED : Generate Rules       : 7.586472e-01
ELAPSED : Solver Init          : 2.482009e-01
ELAPSED : SAT Solve            : 5.968580e-01
```

Which is not very helpful
