### ISSUE TITLE
Policy should never suggest literal for which it lacks clauses

### ISSUE THREAD

**Issue by noraderam** [enthought/sat-solver#217]
This is the cause of the exception in #215. While that situation was only reached because of a broken environment, it shed light on a mistaken assumption.

A policy assumes that it has an entry in `_id_to_clauses` for each literal it suggests. This is not guaranteed based on our current process.

Consider the following test scenario:
```
packages:
    - bar 1.2.3-1
    - bar 1.2.3-2
    - foo 1.2.3-1

remote:
    - bar 1.2.3-1
    - bar 1.2.3-2

installed:
    - foo 1.2.3-1

request:
    - operation: "install"
      requirement: "bar"

transaction:
    - kind: "install"
      package: "bar 1.2.3-2"
```

Because two versions of `bar` are available, we have a non-trivial install request. `foo` is already installed and is only available locally--it is not available in the `remote` repository. Only one package provides `foo` and it has no dependencies or conflicts. In this unique situation, the `RulesGenerator` creates no rules for `foo`. (More discussion: https://github.com/enthought/sat-solver/pull/215#issuecomment-220514010)

The `UndeterminedClausePolicy` draws its candidate literals from the `installed_repository` passed in during instantiation. `clauses` (which are derived from `rules`) are passed in as an argument to `get_next_package_id`. We cannot preemptively trim the potential candidates. We can however make sure that we never suggest a literal which does not exist in any of the known clauses, as tracked in `id_to_clauses`.
